FROM node:20-slim

RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    curl \
    git \
    unzip \
    python3 \
    build-essential \
    jq \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

RUN npm install -g eas-cli expo-cli

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY . .

ARG EXPO_TOKEN
ENV EXPO_TOKEN=$EXPO_TOKEN

ARG EXPO_PUBLIC_GOOGLE_MAPS_API_KEY
ENV EXPO_PUBLIC_GOOGLE_MAPS_API_KEY=$EXPO_PUBLIC_GOOGLE_MAPS_API_KEY

CMD ["/entrypoint.sh"]